// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AuctionSystemClient is the client API for AuctionSystem service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuctionSystemClient interface {
	// get a stream from the server -> client for messages
	Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (AuctionSystem_JoinClient, error)
	// publish a message in the chat
	Publish(ctx context.Context, in *Message, opts ...grpc.CallOption) (*PublishResponse, error)
}

type auctionSystemClient struct {
	cc grpc.ClientConnInterface
}

func NewAuctionSystemClient(cc grpc.ClientConnInterface) AuctionSystemClient {
	return &auctionSystemClient{cc}
}

func (c *auctionSystemClient) Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (AuctionSystem_JoinClient, error) {
	stream, err := c.cc.NewStream(ctx, &AuctionSystem_ServiceDesc.Streams[0], "/proto.AuctionSystem/Join", opts...)
	if err != nil {
		return nil, err
	}
	x := &auctionSystemJoinClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AuctionSystem_JoinClient interface {
	Recv() (*Message, error)
	grpc.ClientStream
}

type auctionSystemJoinClient struct {
	grpc.ClientStream
}

func (x *auctionSystemJoinClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *auctionSystemClient) Publish(ctx context.Context, in *Message, opts ...grpc.CallOption) (*PublishResponse, error) {
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, "/proto.AuctionSystem/Publish", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuctionSystemServer is the server API for AuctionSystem service.
// All implementations must embed UnimplementedAuctionSystemServer
// for forward compatibility
type AuctionSystemServer interface {
	// get a stream from the server -> client for messages
	Join(*JoinRequest, AuctionSystem_JoinServer) error
	// publish a message in the chat
	Publish(context.Context, *Message) (*PublishResponse, error)
	mustEmbedUnimplementedAuctionSystemServer()
}

// UnimplementedAuctionSystemServer must be embedded to have forward compatible implementations.
type UnimplementedAuctionSystemServer struct {
}

func (UnimplementedAuctionSystemServer) Join(*JoinRequest, AuctionSystem_JoinServer) error {
	return status.Errorf(codes.Unimplemented, "method Join not implemented")
}
func (UnimplementedAuctionSystemServer) Publish(context.Context, *Message) (*PublishResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedAuctionSystemServer) mustEmbedUnimplementedAuctionSystemServer() {}

// UnsafeAuctionSystemServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuctionSystemServer will
// result in compilation errors.
type UnsafeAuctionSystemServer interface {
	mustEmbedUnimplementedAuctionSystemServer()
}

func RegisterAuctionSystemServer(s grpc.ServiceRegistrar, srv AuctionSystemServer) {
	s.RegisterService(&AuctionSystem_ServiceDesc, srv)
}

func _AuctionSystem_Join_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(JoinRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AuctionSystemServer).Join(m, &auctionSystemJoinServer{stream})
}

type AuctionSystem_JoinServer interface {
	Send(*Message) error
	grpc.ServerStream
}

type auctionSystemJoinServer struct {
	grpc.ServerStream
}

func (x *auctionSystemJoinServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func _AuctionSystem_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionSystemServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AuctionSystem/Publish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionSystemServer).Publish(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

// AuctionSystem_ServiceDesc is the grpc.ServiceDesc for AuctionSystem service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuctionSystem_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AuctionSystem",
	HandlerType: (*AuctionSystemServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Publish",
			Handler:    _AuctionSystem_Publish_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Join",
			Handler:       _AuctionSystem_Join_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/AuctionSystem.proto",
}
